// khai báo url
const splashRoute = "/";
const welcomeRoute = "/welcome";
const feedRoute = "/feed";
const monitorRoute = "/monitor";
const profileRoute = "/profile";
const settingsRoute = "/settings";
const messagingRoute = "/messaging";
const signupRoute = "/signup";
const loginRoute = "/login";
const forgetRoute = "/forget";
const verifyRoute = "/verify";
const changePasswordRoute = "/change_password";
const imageRoute = "/image";
const searchRoute = "/search";
const registerClassHome = "/register_class";
