// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKI5TEhkOmhmyH3YY1b78RUkvYwlFjsc',
    appId: '1:897529918419:web:b61e9a989cab8466f9f526',
    messagingSenderId: '897529918419',
    projectId: 'app-qldt',
    authDomain: 'app-qldt.firebaseapp.com',
    storageBucket: 'app-qldt.firebasestorage.app',
    measurementId: 'G-YB0BNRBPWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // current_key
    apiKey: 'AIzaSyD_ZD2aFvMCId2fWQ--byva2YQrpt2C1gU',
    // mobilesdk_app_id
    appId: '1:844626516109:android:1c122a7d1d7acc8ffd2ac4',
    // project_number
    messagingSenderId: '844626516109',
    // project_id
    projectId: 'crossplatform-it4788-f38e0',
    // storage_bucket
    storageBucket: 'crossplatform-it4788-f38e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJQzxr5SaDOE9OBo0-lbEkxdmT3czAjQo',
    appId: '1:897529918419:ios:addd9d02b12e3edff9f526',
    messagingSenderId: '897529918419',
    projectId: 'app-qldt',
    storageBucket: 'app-qldt.firebasestorage.app',
    iosBundleId: 'com.example.appQldt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJQzxr5SaDOE9OBo0-lbEkxdmT3czAjQo',
    appId: '1:897529918419:ios:addd9d02b12e3edff9f526',
    messagingSenderId: '897529918419',
    projectId: 'app-qldt',
    storageBucket: 'app-qldt.firebasestorage.app',
    iosBundleId: 'com.example.appQldt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBKI5TEhkOmhmyH3YY1b78RUkvYwlFjsc',
    appId: '1:897529918419:web:98ce1b9589575174f9f526',
    messagingSenderId: '897529918419',
    projectId: 'app-qldt',
    authDomain: 'app-qldt.firebaseapp.com',
    storageBucket: 'app-qldt.firebasestorage.app',
    measurementId: 'G-XTH94SY6GC',
  );

}