// map lỗi theo JSON
const errorMap = {
  1000: "OK",
  9995: "Định dạng email không chính xác",
  9994: "Mật khẩu không hợp lệ (Giới hạn 6 - 15 ký tự)",
  9996: "Email đã tồn tại",
  1011: "Định dạng email không chính xác",

  1001: "Tham số không hợp lệ.",
  1002: "Lỗi kết nối tới cơ sở dữ liệu.",
  1003: "Tài khoản đã tồn tại.",
  1004: "Đã hết phiên làm việc.",
  1005: "Token không tồn tại.",
  1006: "Sai loại token.",
  1007: "Access token không hợp lệ",
  1008: "Sai tài khoản hoặc mật khẩu.",
  1009: "Tài khoản không tồn tại.",
  1010: "Thiết bị không có trong hệ thống.",

  1012: "Mã xác nhận đã hết hạn. Hãy gửi lại mã xác nhận.",
  1013: "Tài khoản đã được xác nhận.",
  1014: "Tài khoản đã bị khóa.",
  1015: "Tài khoản chưa khởi tạo xong.",
  1016: "Người dùng không tồn tại trong hệ thống.",
  1017: "Bạn phải nhập mã xác nhận đã được gửi qua email.",
  1018: "Mã xác nhận không chính xác.",
  1019: "Refresh token không hợp lệ.",
  1020: "Refresh token đã hết hạn.",
  1021: "Access token và refresh token không khớp.",
  1022: "Access token không tồn tại trong cơ sở dữ liệu.",
  1023: "Refresh token không tồn tại trong cơ sở dữ liệu.",
  1024: "Mật khẩu cũ không hợp lệ.",
  1025:
      "Hệ thống không biết bạn muốn xác nhận gì. Hãy yêu cầu lại mã và xác nhận lại.",
  1026:
      "Xác thực với cơ sở dữ liệu thất bại. Hãy yêu cầu lại mã và xác nhận lại.",
  1027: "Thiết bị tồn tại trong hệ thống.",
  1028: "Tài khoản phải đổi mật khẩu",
  1029: "Tài khoản phải được xác thực bằng thiết bị gốc.",
  1030: "Thông tin thiết bị không hợp lệ.",
  1031: "Bạn phải dùng ID của thiết bị truy cập.",
  1032: "Thiết bị hiện tại không phải thiết bị gốc.",
  1033: "Không có thiết bị truy cập",
  1034: "Access token không tồn tại trong cơ sở dữ liệu.",
  1035: "Refresh token không tồn tại trong cơ sở dữ liệu.",
  1036: "Trường học không tồn tại trong cơ sở dữ liệu."
};
